### ISSUE TITLE
Engine crash

### ISSUE THREAD

**Issue by fabianvdW** [fabianvdW/FabChess#34]
Discovered in a quick 3 thread arena test with FabChess version 1.14. 
Errror log:
```
2020-04-05 02:41:56,872-->2:position startpos moves d2d4 g8f6 c2c4 g7g6 b1c3 d7d5 g1f3 f8g7 e2e3 e8g8 c4d5 f6d5 f1c4 d5b6 c4b3 b8c6 e1g1 e7e5 d4d5 c6a5 e3e4 c8g4 h2h3 a5b3 a2b3 g4f3 d1f3 a7a6 c1e3 d8d6 f3d1 f7f5 f2f3 b6d7 d1c2 a8c8 e3f2 f5f4 f1d1 f8d8 d1d3 g7f8 c3e2 d7f6 b3b4 d6d7 c2c3 d7e8 f2c5 f8d6 e2f4 f6e4 f3e4 e5f4 a1e1 c7c6 d5c6 c8c6 c3c4 e8f7 d3d5 c6c8 e1d1 d8e8 c4d4 d6e7 d1f1 b7b5 e4e5 g6g5 h3h4 e8d8 d5d8 c8d8 d4e4 d8e8 h4g5 e7g5 c5d6 g8h8 f1a1 f7b3 e4e2 e8e6 d6c5 g5e7 c5e7 e6e7 a1a6 b3e3 e2e3 f4e3 e5e6 h8g7 a6b6 g7f6 b6b5 f6e6 g1f1 e6d6 b5h5 e3e2 f1e1 d6c6 g2g4
2020-04-05 02:41:56,872-->2:go wtime 26571 btime 78949 winc 3000 binc 3000
2020-04-05 02:41:56,873<--2:info depth 1 seldepth 0 nodes 0 nps 0 hashfull 737 time 0 score cp -46 pv c6b6 
2020-04-05 02:41:56,874<--2:info depth 2 seldepth 0 nodes 0 nps 0 hashfull 737 time 0 score cp -29 pv c6b6 h5e5 
2020-04-05 02:41:56,876<--2:info depth 2 seldepth 0 nodes 0 nps 0 hashfull 737 time 0 score cp -14 pv c6b6 e1d2 
2020-04-05 02:41:56,877<--2:info depth 3 seldepth 0 nodes 0 nps 0 hashfull 737 time 0 score cp 0 pv c6b6 g4g5 e7e3 
2020-04-05 02:41:56,879<--2:info depth 4 seldepth 0 nodes 0 nps 0 hashfull 737 time 0 score cp -45 pv c6b6 h5h2 b6c6 h2e2 
2020-04-05 02:41:56,881<--2:info depth 4 seldepth 0 nodes 0 nps 0 hashfull 737 time 0 score cp -45 pv c6b6 h5h2 b6c6 h2e2 
2020-04-05 02:41:56,883<--2:info depth 5 seldepth 0 nodes 0 nps 0 hashfull 737 time 0 score cp -43 pv c6b6 g4g5 e7c7 
2020-04-05 02:41:56,887<--2:info depth 4 seldepth 0 nodes 0 nps 0 hashfull 737 time 0 score cp -24 pv c6b6 b4b5 b6a5 e1d2 
2020-04-05 02:41:56,890<--2:info depth 4 seldepth 0 nodes 0 nps 0 hashfull 737 time 0 score cp -50 pv c6b6 h5h2 e7g7 e1e2 
2020-04-05 02:41:56,892<--2:info depth 5 seldepth 0 nodes 0 nps 0 hashfull 737 time 0 score cp -43 pv c6b6 g4g5 e7e3 
2020-04-05 02:41:56,894<--2:info depth 4 seldepth 0 nodes 0 nps 0 hashfull 737 time 0 score cp -45 pv c6b6 h5h2 b6a6 h2e2 
2020-04-05 02:41:56,896<--2:info depth 4 seldepth 0 nodes 0 nps 0 hashfull 737 time 0 score cp -49 pv e7g7 e1e2 c6b6 
2020-04-05 02:41:56,898<--2:info depth 5 seldepth 0 nodes 0 nps 0 hashfull 737 time 0 score cp -50 pv c6b6 h5h2 e7g7 e1e2 g7g4 
2020-04-05 02:41:56,902<--2:info depth 5 seldepth 0 nodes 0 nps 0 hashfull 737 time 0 score cp -49 pv e7g7 e1e2 c6b6 
2020-04-05 02:41:56,904<--2:info depth 5 seldepth 0 nodes 0 nps 0 hashfull 737 time 0 score cp -50 pv c6b6 h5h2 e7e4 h2e2 e4g4 
2020-04-05 02:41:56,906<--2:info depth 5 seldepth 0 nodes 0 nps 0 hashfull 737 time 0 score cp -46 pv c6b6 h5h2 b6b5 h2e2 e7e2 e1e2 b5b4 
2020-04-05 02:41:56,908<--2:info depth 6 seldepth 0 nodes 0 nps 0 hashfull 737 time 1 score cp -50 pv c6b6 h5h2 e7e4 g4g5 b6b5 h2h7 b5b4 
2020-04-05 02:41:56,910<--2:info depth 7 seldepth 0 nodes 0 nps 0 hashfull 737 time 1 score cp -60 pv c6b6 h5h2 b6b5 h2e2 e7e2 e1e2 b5c4 e2d2 c4b4 
2020-04-05 02:41:56,912<--2:info depth 7 seldepth 0 nodes 0 nps 0 hashfull 737 time 1 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 
2020-04-05 02:41:56,914<--2:info depth 8 seldepth 0 nodes 0 nps 0 hashfull 737 time 2 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 h2d2 
2020-04-05 02:41:56,918<--2:info depth 9 seldepth 0 nodes 0 nps 0 hashfull 737 time 3 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 h2d2 g7f7 f3g3 
2020-04-05 02:41:56,920<--2:info depth 10 seldepth 0 nodes 0 nps 0 hashfull 737 time 3 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 h2d2 b4c4 f3f4 
2020-04-05 02:41:56,922<--2:info depth 11 seldepth 17 nodes 24576 nps 4096000 hashfull 737 time 6 score cp -50 pv c6b6 h5h2 b6b5 h2e2 e7e2 e1e2 b5b4 e2f3 b4c4 f3f4 c4b3 f4e5 
2020-04-05 02:41:56,925<--2:info depth 12 seldepth 17 nodes 24576 nps 3072000 hashfull 737 time 8 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 h2d2 b4c4 f3f4 c4b3 g4g5 
2020-04-05 02:41:56,927<--2:info depth 13 seldepth 19 nodes 40960 nps 3413333 hashfull 737 time 12 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 h2h6 g7b7 h6f6 b4b3 f6c6 b3b2 
2020-04-05 02:41:56,930<--2:info depth 15 seldepth 21 nodes 98304 nps 4681142 hashfull 737 time 21 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 h2d2 b4c4 f3f4 c4b3 d2d5 g7e7 d5b5 b3c4 b5b6 
2020-04-05 02:41:56,932<--2:info depth 16 seldepth 22 nodes 163840 nps 4964848 hashfull 737 time 33 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 h2d2 b4c4 f3f4 c4b3 g4g5 g7f7 f4e5 f7c7 d2d5 c7c2 
2020-04-05 02:41:56,934<--2:info depth 17 seldepth 22 nodes 188416 nps 4710400 hashfull 737 time 40 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 h2d2 b4c4 f3f4 c4b3 g4g5 g7f7 f4e5 f7b7 e5e6 b7b6 d2d6 b6d6 e6d6 
2020-04-05 02:41:56,936<--2:info depth 18 seldepth 25 nodes 311296 nps 5020903 hashfull 737 time 62 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 h2d2 b4b3 f3f4 g7f7 f4e4 f7c7 g4g5 c7e7 e4f5 e7c7 f5e6 c7c6 d2d6 c6d6 e6d6 
2020-04-05 02:41:56,954<--2:info depth 19 seldepth 25 nodes 401408 nps 5017600 hashfull 737 time 80 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 h2d2 b4c4 f3f4 c4b3 g4g5 g7f7 f4e5 f7e7 e5f6 e7c7 d2e2 c7c4 e2e7 c4c6 f6f7 
2020-04-05 02:41:56,986<--2:info depth 19 seldepth 27 nodes 565248 nps 5046857 hashfull 737 time 112 score cp -49 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 h2d2 b4c4 f3f4 c4b3 g4g5 g7b7 f4e5 b7f7 e5e4 f7a7 d2d3 b3b2 e4d5 
2020-04-05 02:41:56,994<--2:info depth 20 seldepth 27 nodes 614400 nps 5120000 hashfull 737 time 120 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 h2d2 b4b3 f3f4 g7e7 f4g5 e7c7 g5h6 c7f7 d2d8 f7b7 h6h5 b7b4 g4g5 
2020-04-05 02:41:57,033<--2:info depth 21 seldepth 30 nodes 827392 nps 5203723 hashfull 737 time 159 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 h2d2 b4c4 f3f4 c4b3 g4g5 g7b7 f4e5 b7f7 e5e4 f7a7 e4f5 a7a5 f5f4 a5a6 d2d7 
2020-04-05 02:41:57,153<--2:info depth 22 seldepth 30 nodes 1433600 nps 5119999 hashfull 737 time 280 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 f3f4 b4b3 h2d2 b3c4 g4g5 g7e7 f4f5 c4b3 f5f6 e7c7 d2e2 c7c4 e2e7 c4c6 f6f5 c6c5 f5f6 
2020-04-05 02:41:57,303<--2:info depth 23 seldepth 30 nodes 2269184 nps 5277172 hashfull 737 time 430 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 f3f4 b4b3 h2d2 b3c4 g4g5 g7e7 f4f5 c4b3 f5f6 e7c7 d2e2 c7d7 f6f5 d7c7 e2e3 b3b2 f5f6 
2020-04-05 02:41:57,462<--2:info depth 24 seldepth 31 nodes 3145728 nps 5349877 hashfull 737 time 588 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 f3f4 b4b3 h2d2 b3c4 g4g5 g7e7 f4f5 c4b3 f5f6 e7c7 d2e2 c7d7 e2e7 d7e7 f6e7 b3b2 e7f6 
2020-04-05 02:41:57,701<--2:info depth 25 seldepth 34 nodes 4333568 nps 5240106 hashfull 737 time 827 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 f3f4 b4b3 h2d2 b3c4 g4g5 c4b3 f4f5 g7f7 f5e5 f7b7 e5e6 b7b5 d2d5 b5b7 d5d7 b7d7 e6d7 b3b2 d7e6 
2020-04-05 02:41:57,807<--2:info depth 26 seldepth 34 nodes 4833280 nps 5174817 hashfull 737 time 934 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 f3f4 b4b3 h2d2 b3c4 g4g5 c4b3 f4f5 b3c4 d2c2 c4b3 c2g2 g7d7 f5e6 d7c7 g2e2 c7g7 e6f6 g7d7 e2e8 d7d2 
2020-04-05 02:41:58,379<--2:thread '<unnamed>' panicked at 'King has no phase score', src\board_representation\game_state.rs:115:32
2020-04-05 02:41:58,380<--2:stack backtrace:
2020-04-05 02:41:58,420<--2:   0: backtrace::backtrace::dbghelp::trace
2020-04-05 02:41:58,421<--2:             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace/dbghelp.rs:88
2020-04-05 02:41:58,422<--2:   1: backtrace::backtrace::trace_unsynchronized
2020-04-05 02:41:58,423<--2:             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.40\src\backtrace/mod.rs:66
2020-04-05 02:41:58,424<--2:   2: std::sys_common::backtrace::_print_fmt
2020-04-05 02:41:58,425<--2:             at src\libstd\sys_common/backtrace.rs:84
2020-04-05 02:41:58,426<--2:   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
2020-04-05 02:41:58,427<--2:             at src\libstd\sys_common/backtrace.rs:61
2020-04-05 02:41:58,428<--2:   4: core::fmt::write
2020-04-05 02:41:58,429<--2:             at src\libcore\fmt/mod.rs:1025
2020-04-05 02:41:58,430<--2:   5: std::io::Write::write_fmt
2020-04-05 02:41:58,430<--2:             at src\libstd\io/mod.rs:1426
2020-04-05 02:41:58,430<--2:   6: std::sys_common::backtrace::_print
2020-04-05 02:41:58,430<--2:             at src\libstd\sys_common/backtrace.rs:65
2020-04-05 02:41:58,430<--2:   7: std::sys_common::backtrace::print
2020-04-05 02:41:58,430<--2:             at src\libstd\sys_common/backtrace.rs:50
2020-04-05 02:41:58,430<--2:   8: std::panicking::default_hook::{{closure}}
2020-04-05 02:41:58,430<--2:             at src\libstd/panicking.rs:193
2020-04-05 02:41:58,430<--2:   9: std::panicking::default_hook
2020-04-05 02:41:58,430<--2:             at src\libstd/panicking.rs:210
2020-04-05 02:41:58,430<--2:  10: std::panicking::rust_panic_with_hook
2020-04-05 02:41:58,431<--2:             at src\libstd/panicking.rs:471
2020-04-05 02:41:58,431<--2:  11: std::panicking::begin_panic
2020-04-05 02:41:58,431<--2:  12: core::move_generation::makemove::make_move
2020-04-05 02:41:58,431<--2:  13: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,431<--2:  14: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,431<--2:  15: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,431<--2:  16: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,431<--2:  17: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,431<--2:  18: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,431<--2:  19: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,431<--2:  20: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,431<--2:  21: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,431<--2:  22: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,431<--2:  23: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,431<--2:  24: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,432<--2:  25: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,432<--2:  26: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,432<--2:  27: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,432<--2:  28: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,432<--2:  29: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,432<--2:  30: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,432<--2:  31: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,432<--2:  32: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,432<--2:  33: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,432<--2:  34: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,432<--2:  35: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,432<--2:  36: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,432<--2:  37: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,432<--2:  38: core::search::alphabeta::principal_variation_search
2020-04-05 02:41:58,433<--2:note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2020-04-05 02:41:58,696<--2:info depth 27 seldepth 38 nodes 8519680 nps 4676004 hashfull 738 time 1822 score cp -50 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 f3f4 b4b3 h2d2 b3c4 g4g5 c4b3 f4f5 b3c4 d2c2 c4b3 c2g2 g7d7 f5e6 d7g7 e6f6 g7g6 f6f5 g6g7 g2e2 g7c7 e2e3 b3b2 f5f6 
2020-04-05 02:42:01,161<--2:info depth 28 seldepth 40 nodes 16351232 nps 3814143 hashfull 738 time 4287 score cp -65 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 f3f4 b4b3 h2d2 b3c4 g4g5 c4b3 d2e2 g7f7 f4g4 f7c7 g4h5 b3c4 e2d2 c7c5 d2c2 c4b5 c2c5 b5c5 h5g4 c5c4 g4f5 c4d3 
2020-04-05 02:42:01,181<--2:info depth 28 seldepth 40 nodes 16408576 nps 3808861 hashfull 738 time 4308 score cp -65 pv c6b6 h5h2 e7g7 e1e2 b6b5 e2f3 b5b4 f3f4 b4b3 h2d2 b3c4 g4g5 c4b3 d2e2 g7f7 f4g4 f7c7 g4h5 b3c4 e2d2 c7c5 d2c2 c4b5 c2c5 b5c5 h5g4 c5c4 g4f5 c4d3 
```

**Comment by fabianvdW** [comment]
The error stems from #24, where I removed TT move validation [here](https://github.com/fabianvdW/FabChess/commit/0c0fa198c51d97d726a8d4deca46bd5672cde087#diff-a919d679fd618ac6ac685d9abcb1248aL672) and [here](https://github.com/fabianvdW/FabChess/commit/0c0fa198c51d97d726a8d4deca46bd5672cde087#diff-a919d679fd618ac6ac685d9abcb1248aL683), and forgot to add them back in. The fix should be relativly easy. This is why I should make automated testing.
